package view.employee;

import model.Accounts;
import model.Transactions;
import model.Savings;

import control.AccountsControl;
import control.TransactionsControl;
import control.SavingsControl;
import exception.BlankInputException;
import java.awt.Color;
import java.awt.Font;
import java.awt.geom.RoundRectangle2D;

import java.util.concurrent.ThreadLocalRandom;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

public class TellerSavingsView extends javax.swing.JFrame {
    private AccountsControl aControl;
    private SavingsControl savingControl;
    private TransactionsControl transactionControl;
    private Accounts penyimpan = null;
    private Savings sv = null;
    private boolean isSavingsTableClicked = false;
    
    public void initJFrame(){
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }
    
    public void init(){
        titleBar.initJFram(this);
    }
    
    public void setComponent(boolean value){
        namaMemberInput.setEnabled(value);
        cancelSavingBtn.setEnabled(value);
        jumlahSavingInput.setEnabled(value);
        idSavingInput.setEnabled(value);
        cbSavingType.setEnabled(value);
        setRadio(value);
    }
    
    public void setPenyimpanArea(boolean value){
        noAkunInput.setEnabled(value);
        okSavingBtn.setEnabled(value);
        if(value==true){
            namaMemberInput.setText("");
            noAkunInput.setText("");
        }
    }
    
    public void setRadio(boolean value){
        p1.setEnabled(value);
        p2.setEnabled(value);
        p3.setEnabled(value);
        p4.setEnabled(value);
        p5.setEnabled(value);
    }
    
    public void setRadioButtonValue(){
        p1.setActionCommand("BRI");
        p2.setActionCommand("BNI");
        p3.setActionCommand("DANA");
        p4.setActionCommand("OVO");
        p5.setActionCommand("Tunai");
    }
    
    public void clearText(){
        setPenyimpanArea(true);
        noAkunInput.setText("");
        namaMemberInput.setText("");
        cancelSavingBtn.setEnabled(false);
        idSavingInput.setText("");
        jumlahSavingInput.setText("");
        cbSavingType.setSelectedIndex(0);
        setRadio(false);
    }
    
    public void showSaving(){
        savingsTable.getTableHeader().setFont(new Font("Montserrat", Font.PLAIN, 12));
        savingsTable.getTableHeader().setOpaque(false);
        savingsTable.getTableHeader().setForeground(new Color(0, 61, 121));
        savingsTable.setRowHeight(25);
        savingsTable.setModel(savingControl.showSavings("SV", "", ""));
    }
    
    public TellerSavingsView() {
        initComponents();
        aControl = new AccountsControl();
        transactionControl = new TransactionsControl();
        savingControl = new SavingsControl();
        setComponent(false);
        setRadioButtonValue();
        showSaving();
        initJFrame();
        init();
    }
    
    private void blankInputException() throws BlankInputException{
        if(namaMemberInput.getText().isEmpty() || jumlahSavingInput.getText().isEmpty()){
            throw new BlankInputException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payGrp = new javax.swing.ButtonGroup();
        panelBorder11 = new com.swing.PanelBorder1();
        panelBorder12 = new com.swing.PanelBorder1();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleBar = new javaswingdev.swing.titlebar.TitleBar();
        jLabel9 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        panelBorder13 = new com.swing.PanelBorder1();
        cancelSavingBtn = new javax.swing.JButton();
        noAkunLabel = new javax.swing.JLabel();
        okSavingBtn = new javax.swing.JButton();
        noAkunInput = new javax.swing.JTextField();
        namaMemberLabel = new javax.swing.JLabel();
        namaMemberInput = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        savingTypeLabel = new javax.swing.JLabel();
        cbSavingType = new javax.swing.JComboBox<>();
        panelBorder15 = new com.swing.PanelBorder1();
        jumlahSavingInput = new javax.swing.JTextField();
        idSavingInput = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        panelBorder16 = new com.swing.PanelBorder1();
        jScrollPane1 = new javax.swing.JScrollPane();
        savingsTable = new javax.swing.JTable();
        cancelBtn = new javax.swing.JButton();
        savingBtn = new javax.swing.JButton();
        panelBorder17 = new com.swing.PanelBorder1();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        p1 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        p3 = new javax.swing.JRadioButton();
        p4 = new javax.swing.JRadioButton();
        p5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder11.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder11.setPreferredSize(new java.awt.Dimension(1280, 720));
        panelBorder11.setRoundBottomLeft(20);
        panelBorder11.setRoundBottomRight(20);
        panelBorder11.setRoundTopLeft(20);
        panelBorder11.setRoundTopRight(20);

        panelBorder12.setBackground(new java.awt.Color(28, 94, 32));
        panelBorder12.setPreferredSize(new java.awt.Dimension(1280, 120));
        panelBorder12.setRoundTopLeft(20);
        panelBorder12.setRoundTopRight(20);

        jLabel3.setBackground(new java.awt.Color(28, 94, 32));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Savings");

        jLabel2.setBackground(new java.awt.Color(28, 94, 32));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teller");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sedeng pas.png"))); // NOI18N

        backBtn.setBackground(new java.awt.Color(255, 0, 0));
        backBtn.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder12Layout = new javax.swing.GroupLayout(panelBorder12);
        panelBorder12.setLayout(panelBorder12Layout);
        panelBorder12Layout.setHorizontalGroup(
            panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder12Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 818, Short.MAX_VALUE)
                .addGroup(panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder12Layout.createSequentialGroup()
                        .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder12Layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        panelBorder12Layout.setVerticalGroup(
            panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder12Layout.createSequentialGroup()
                .addGroup(panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBorder12Layout.createSequentialGroup()
                        .addGroup(panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder12Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2))
                            .addGroup(panelBorder12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelBorder12Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder13.setRoundBottomLeft(20);
        panelBorder13.setRoundBottomRight(20);
        panelBorder13.setRoundTopLeft(20);
        panelBorder13.setRoundTopRight(20);

        cancelSavingBtn.setBackground(new java.awt.Color(194, 16, 16));
        cancelSavingBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cancelSavingBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelSavingBtn.setText("Cancel");
        cancelSavingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSavingBtnActionPerformed(evt);
            }
        });

        noAkunLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        noAkunLabel.setText("Number Account");

        okSavingBtn.setBackground(new java.awt.Color(13, 110, 253));
        okSavingBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        okSavingBtn.setForeground(new java.awt.Color(255, 255, 255));
        okSavingBtn.setText("OK");
        okSavingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okSavingBtnActionPerformed(evt);
            }
        });
        okSavingBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okSavingBtnKeyPressed(evt);
            }
        });

        noAkunInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        namaMemberLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        namaMemberLabel.setText("Member Name");

        namaMemberInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(28, 94, 32));
        jLabel19.setText("Member Details");

        jPanel5.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        savingTypeLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        savingTypeLabel.setText("Savings Type");

        cbSavingType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Savings Type", "Wajib", "Pokok", "Sukarela" }));
        cbSavingType.setMinimumSize(new java.awt.Dimension(64, 22));
        cbSavingType.setPreferredSize(new java.awt.Dimension(64, 22));
        cbSavingType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSavingTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder13Layout = new javax.swing.GroupLayout(panelBorder13);
        panelBorder13.setLayout(panelBorder13Layout);
        panelBorder13Layout.setHorizontalGroup(
            panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savingTypeLabel)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addGroup(panelBorder13Layout.createSequentialGroup()
                        .addComponent(noAkunInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(okSavingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(noAkunLabel)
                    .addComponent(cancelSavingBtn)
                    .addComponent(namaMemberLabel)
                    .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbSavingType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namaMemberInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelBorder13Layout.setVerticalGroup(
            panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel19)
                .addGap(2, 2, 2)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noAkunLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noAkunInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okSavingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(namaMemberLabel)
                .addGap(3, 3, 3)
                .addComponent(namaMemberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savingTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSavingType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelSavingBtn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelBorder15.setRoundBottomLeft(20);
        panelBorder15.setRoundBottomRight(20);
        panelBorder15.setRoundTopLeft(20);
        panelBorder15.setRoundTopRight(20);

        jumlahSavingInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jumlahSavingInput.setHighlighter(null);

        idSavingInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        jPanel8.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(28, 94, 32));
        jLabel20.setText("ID Saving");

        jPanel9.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(28, 94, 32));
        jLabel21.setText("Saving Amount");

        javax.swing.GroupLayout panelBorder15Layout = new javax.swing.GroupLayout(panelBorder15);
        panelBorder15.setLayout(panelBorder15Layout);
        panelBorder15Layout.setHorizontalGroup(
            panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder15Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idSavingInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jumlahSavingInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        panelBorder15Layout.setVerticalGroup(
            panelBorder15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder15Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addGap(2, 2, 2)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idSavingInput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel21)
                .addGap(2, 2, 2)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jumlahSavingInput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        panelBorder16.setRoundBottomLeft(20);
        panelBorder16.setRoundBottomRight(20);
        panelBorder16.setRoundTopLeft(20);
        panelBorder16.setRoundTopRight(20);

        savingsTable.setAutoCreateRowSorter(true);
        savingsTable.setBackground(new java.awt.Color(255, 254, 243));
        savingsTable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        savingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        savingsTable.setGridColor(new java.awt.Color(204, 204, 204));
        savingsTable.setRowHeight(25);
        savingsTable.setSelectionBackground(new java.awt.Color(93, 143, 44));
        savingsTable.setShowGrid(true);
        savingsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savingsTableMouseClicked(evt);
            }
        });
        savingsTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                savingsTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(savingsTable);

        javax.swing.GroupLayout panelBorder16Layout = new javax.swing.GroupLayout(panelBorder16);
        panelBorder16.setLayout(panelBorder16Layout);
        panelBorder16Layout.setHorizontalGroup(
            panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder16Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelBorder16Layout.setVerticalGroup(
            panelBorder16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder16Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        cancelBtn.setBackground(new java.awt.Color(194, 16, 16));
        cancelBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        savingBtn.setBackground(new java.awt.Color(25, 135, 84));
        savingBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        savingBtn.setForeground(new java.awt.Color(255, 255, 255));
        savingBtn.setText("Saving");
        savingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingBtnActionPerformed(evt);
            }
        });

        panelBorder17.setRoundBottomLeft(20);
        panelBorder17.setRoundBottomRight(20);
        panelBorder17.setRoundTopLeft(20);
        panelBorder17.setRoundTopRight(20);

        jPanel6.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel22.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(28, 94, 32));
        jLabel22.setText("Payment Methods");

        payGrp.add(p1);
        p1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        p1.setText("BRI");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        payGrp.add(p2);
        p2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        p2.setText("BNI");
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        payGrp.add(p3);
        p3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        p3.setText("DANA");
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });

        payGrp.add(p4);
        p4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        p4.setText("OVO");
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });

        payGrp.add(p5);
        p5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        p5.setText("Tunai");
        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder17Layout = new javax.swing.GroupLayout(panelBorder17);
        panelBorder17.setLayout(panelBorder17Layout);
        panelBorder17Layout.setHorizontalGroup(
            panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder17Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder17Layout.setVerticalGroup(
            panelBorder17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder17Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel22)
                .addGap(2, 2, 2)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p5)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBorder11Layout = new javax.swing.GroupLayout(panelBorder11);
        panelBorder11.setLayout(panelBorder11Layout);
        panelBorder11Layout.setHorizontalGroup(
            panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder11Layout.createSequentialGroup()
                .addComponent(panelBorder12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelBorder11Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder11Layout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(savingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBorder16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder11Layout.setVerticalGroup(
            panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder11Layout.createSequentialGroup()
                .addComponent(panelBorder12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder11Layout.createSequentialGroup()
                        .addComponent(panelBorder15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBorder11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBorder11Layout.createSequentialGroup()
                        .addComponent(panelBorder13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelBorder17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelBorder16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelSavingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSavingBtnActionPerformed
        setPenyimpanArea(true);
        setComponent(false);
    }//GEN-LAST:event_cancelSavingBtnActionPerformed

    private void okSavingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okSavingBtnActionPerformed

        penyimpan = aControl.searchAccount(Integer.parseInt(noAkunInput.getText()));
        if(penyimpan!=null){
            namaMemberInput.setText(penyimpan.getMember().getFirst_name()+" "+penyimpan.getMember().getLast_name());
            setPenyimpanArea(false);
            cbSavingType.setEnabled(true);
            setRadio(true);
            cancelSavingBtn.setEnabled(true);
            jumlahSavingInput.setEnabled(true);
            idSavingInput.setText("SV-"+String.valueOf(ThreadLocalRandom.current().nextInt(0, 99999)));
        }else{
            JOptionPane.showMessageDialog(null, "Account not found !");
        }
    }//GEN-LAST:event_okSavingBtnActionPerformed

    private void okSavingBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okSavingBtnKeyPressed
        penyimpan = aControl.searchAccount(Integer.parseInt(noAkunInput.getText()));
        if(penyimpan!=null){
            namaMemberInput.setText(penyimpan.getMember().getFirst_name()+" "+penyimpan.getMember().getLast_name());
            setPenyimpanArea(false);
            cancelSavingBtn.setEnabled(true);
            setRadio(true);
            idSavingInput.setText("SV-"+String.valueOf(ThreadLocalRandom.current().nextInt(0, 99999)));
        }else{
            JOptionPane.showMessageDialog(null, "Account not found !");
        }
    }//GEN-LAST:event_okSavingBtnKeyPressed

    private void cbSavingTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSavingTypeActionPerformed
        if(!isSavingsTableClicked){
            if(cbSavingType.getSelectedItem().equals("Wajib")){
                jumlahSavingInput.setText("200000");
                jumlahSavingInput.setEnabled(false);
            }else{
                jumlahSavingInput.setText("");
                jumlahSavingInput.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cbSavingTypeActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        clearText();
        showSaving();
        setComponent(false);
    }//GEN-LAST:event_cancelBtnActionPerformed
   
    private void savingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingBtnActionPerformed
        try{
            blankInputException();
            int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Are you sure to saving?", "Confirmation",JOptionPane.YES_NO_OPTION);
            switch (getAnswer) {
                case 0:
                transactionControl.insertTransaction(new Transactions("SV-"+String.valueOf(ThreadLocalRandom.current().nextInt(0, 99999)),
                    Integer.parseInt(noAkunInput.getText()), idSavingInput.getText(), LocalDate.now().toString()));
                savingControl.insertSavings(new Savings(idSavingInput.getText(), cbSavingType.getSelectedItem().toString(), LocalDate.now().toString(), payGrp.getSelection().toString(), Double.parseDouble(jumlahSavingInput.getText()), Integer.parseInt(noAkunInput.getText())));
        JOptionPane.showMessageDialog(null, "Saving success !");
        clearText();
        break;

        case 1:
        //do nothing
        break;
        default:
        throw new AssertionError();
        }
        }catch(BlankInputException e){
            JOptionPane.showConfirmDialog(null, e.message(), "Warning", JOptionPane.DEFAULT_OPTION);
            System.out.println("Error: " + e.toString());
        }catch(NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Amount Saving Must Be Number ! ", "Warning", JOptionPane.DEFAULT_OPTION);
            System.out.println("Error: " + e.toString());
        }
        showSaving();
    }//GEN-LAST:event_savingBtnActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_p1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3ActionPerformed

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4ActionPerformed

    private void savingsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_savingsTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsTableKeyPressed

    private void savingsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savingsTableMouseClicked
        isSavingsTableClicked = true;
        noAkunInput.setEnabled(false);
        okSavingBtn.setEnabled(false);
        jumlahSavingInput.setEnabled(false);
        cbSavingType.setEnabled(false);
        setRadio(false);
        
        int clickedRow = savingsTable.getSelectedRow();
        TableModel tableModel = savingsTable.getModel();
        
        noAkunInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        Accounts p = aControl.searchAccount(Integer.parseInt((noAkunInput.getText())));
        namaMemberInput.setText(p.getMember().getFirst_name()+" "+p.getMember().getLast_name());
        jumlahSavingInput.setText(tableModel.getValueAt(clickedRow, 5).toString());
        idSavingInput.setText(tableModel.getValueAt(clickedRow, 1).toString());
        cbSavingType.setSelectedItem(tableModel.getValueAt(clickedRow, 2).toString());
        savingBtn.setEnabled(false);
        String radio = tableModel.getValueAt(clickedRow, 6).toString();
        switch(radio){
            case "BRI" :
                p1.setSelected(true);
                break;
            case "BNI" :
                p2.setSelected(true);
                break;
            case "DANA":
                p3.setSelected(true);
                break;
            case "OVO":
                p4.setSelected(true);
                break;
            case "Tunai":
                p5.setSelected(true);
                break;
        }
        isSavingsTableClicked = false;
    }//GEN-LAST:event_savingsTableMouseClicked

    private void p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        DashTellerView dv = new DashTellerView();
        this.dispose();
        dv.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TellerSavingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TellerSavingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TellerSavingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TellerSavingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TellerSavingsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelSavingBtn;
    private javax.swing.JComboBox<String> cbSavingType;
    private javax.swing.JTextField idSavingInput;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahSavingInput;
    private javax.swing.JTextField namaMemberInput;
    private javax.swing.JLabel namaMemberLabel;
    private javax.swing.JTextField noAkunInput;
    private javax.swing.JLabel noAkunLabel;
    private javax.swing.JButton okSavingBtn;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p2;
    private javax.swing.JRadioButton p3;
    private javax.swing.JRadioButton p4;
    private javax.swing.JRadioButton p5;
    private com.swing.PanelBorder1 panelBorder11;
    private com.swing.PanelBorder1 panelBorder12;
    private com.swing.PanelBorder1 panelBorder13;
    private com.swing.PanelBorder1 panelBorder15;
    private com.swing.PanelBorder1 panelBorder16;
    private com.swing.PanelBorder1 panelBorder17;
    private javax.swing.ButtonGroup payGrp;
    private javax.swing.JButton savingBtn;
    private javax.swing.JLabel savingTypeLabel;
    private javax.swing.JTable savingsTable;
    private javaswingdev.swing.titlebar.TitleBar titleBar;
    // End of variables declaration//GEN-END:variables
}
