package view.members;

import java.awt.geom.RoundRectangle2D;
import connection.DbConnection;
import model.Accounts;
import model.Members;
import control.AccountsControl;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class LoginMembersView extends javax.swing.JFrame {

    private AccountsControl aControl = new AccountsControl();
    
    public void initJFrame(){
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
        setBackground(new Color(0, 0, 0, 0));
    }
    
    public LoginMembersView() {
        initComponents();
        initJFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder12 = new com.swing.PanelBorder1();
        panelBorder13 = new com.swing.PanelBorder1();
        jLabel3 = new javax.swing.JLabel();
        loginlabel3 = new javax.swing.JLabel();
        loginlabel4 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        userlabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        loginlabel1 = new javax.swing.JLabel();
        loginlabel2 = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        loginlabel = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        exPanel = new com.swing.PanelBorder1();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder12.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder12.setPreferredSize(new java.awt.Dimension(395, 917));
        panelBorder12.setRoundBottomLeft(20);
        panelBorder12.setRoundBottomRight(20);
        panelBorder12.setRoundTopLeft(20);
        panelBorder12.setRoundTopRight(20);

        panelBorder13.setBackground(new java.awt.Color(28, 94, 32));
        panelBorder13.setRoundBottomLeft(100);
        panelBorder13.setRoundBottomRight(100);
        panelBorder13.setRoundTopLeft(20);
        panelBorder13.setRoundTopRight(20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/725.png"))); // NOI18N

        loginlabel3.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        loginlabel3.setForeground(new java.awt.Color(255, 255, 255));
        loginlabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlabel3.setText("Koperasi");

        loginlabel4.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        loginlabel4.setForeground(new java.awt.Color(255, 255, 255));
        loginlabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlabel4.setText("Simpan Pinjam");

        javax.swing.GroupLayout panelBorder13Layout = new javax.swing.GroupLayout(panelBorder13);
        panelBorder13.setLayout(panelBorder13Layout);
        panelBorder13Layout.setHorizontalGroup(
            panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder13Layout.createSequentialGroup()
                .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder13Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3))
                    .addGroup(panelBorder13Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginlabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder13Layout.createSequentialGroup()
                                .addComponent(loginlabel3)
                                .addGap(35, 35, 35)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder13Layout.setVerticalGroup(
            panelBorder13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(loginlabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginlabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        loginBtn.setBackground(new java.awt.Color(28, 94, 32));
        loginBtn.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(245, 245, 245));
        loginBtn.setText("Login");
        loginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        loginBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtnFocusGained(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginBtnKeyPressed(evt);
            }
        });

        userlabel.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        userlabel.setForeground(new java.awt.Color(28, 94, 32));
        userlabel.setText("Username");

        passwordInput.setBackground(new java.awt.Color(255, 255, 255));
        passwordInput.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        passwordInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 94, 32), 2, true));
        passwordInput.setPreferredSize(new java.awt.Dimension(64, 27));

        loginlabel1.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        loginlabel1.setForeground(new java.awt.Color(28, 94, 32));
        loginlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlabel1.setText("Welcome Back");

        loginlabel2.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        loginlabel2.setForeground(new java.awt.Color(28, 94, 32));
        loginlabel2.setText("LOGIN");

        passlabel.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        passlabel.setForeground(new java.awt.Color(28, 94, 32));
        passlabel.setText("Password");

        loginlabel.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        loginlabel.setForeground(new java.awt.Color(28, 94, 32));
        loginlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlabel.setText("Please enter your username and password");

        userInput.setBackground(new java.awt.Color(255, 255, 255));
        userInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 94, 32), 2, true));
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });

        exPanel.setBackground(new java.awt.Color(0, 0, 0));
        exPanel.setPreferredSize(new java.awt.Dimension(170, 6));
        exPanel.setRoundBottomLeft(20);
        exPanel.setRoundBottomRight(20);
        exPanel.setRoundTopLeft(20);
        exPanel.setRoundTopRight(20);
        exPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exPanelLayout = new javax.swing.GroupLayout(exPanel);
        exPanel.setLayout(exPanelLayout);
        exPanelLayout.setHorizontalGroup(
            exPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        exPanelLayout.setVerticalGroup(
            exPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBorder12Layout = new javax.swing.GroupLayout(panelBorder12);
        panelBorder12.setLayout(panelBorder12Layout);
        panelBorder12Layout.setHorizontalGroup(
            panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(panelBorder12Layout.createSequentialGroup()
                .addGroup(panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder12Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginlabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userlabel)
                                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passlabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder12Layout.createSequentialGroup()
                                .addComponent(loginlabel2)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder12Layout.createSequentialGroup()
                                .addComponent(loginlabel1)
                                .addGap(45, 45, 45))))
                    .addGroup(panelBorder12Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(exPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelBorder12Layout.setVerticalGroup(
            panelBorder12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder12Layout.createSequentialGroup()
                .addComponent(panelBorder13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginlabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginlabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder12, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnFocusGained

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        Accounts a = aControl.checkLoginAccount(userInput.getText(), String.valueOf(passwordInput.getPassword()));
        if(a==null){ 
            JOptionPane.showMessageDialog(null, "Username atau password salah!");
            return;
        }
        
        this.dispose();
        DashMembersView mv = new DashMembersView(a);
        mv.setVisible(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void loginBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginBtnKeyPressed
        Accounts a = aControl.checkLoginAccount(userInput.getText(), String.valueOf(passwordInput.getPassword()));
        if(a==null){ 
            JOptionPane.showMessageDialog(null, "Username atau password salah!");
            return;
        }

        this.dispose();
        DashMembersView mv = new DashMembersView(a);
        mv.setVisible(true);
    }//GEN-LAST:event_loginBtnKeyPressed

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed

    private void exPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exPanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMembersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMembersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMembersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMembersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMembersView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.swing.PanelBorder1 exPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JLabel loginlabel1;
    private javax.swing.JLabel loginlabel2;
    private javax.swing.JLabel loginlabel3;
    private javax.swing.JLabel loginlabel4;
    private com.swing.PanelBorder1 panelBorder12;
    private com.swing.PanelBorder1 panelBorder13;
    private javax.swing.JLabel passlabel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField userInput;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
